name: location_web
description: The web implementation of the location plugin.
version: 5.0.1
homepage: https://github.com/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
issue_tracker: https://github.com/Lyokone/flutterlocation/issues
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.2
  js: ^0.6.3
  location_platform_interface:
    git:
      url: git@github.com:craggy2593/flutterlocation.git
      path: packages/location_platform_interface
      ref: fix/backround-location-mar-24
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      web:
        pluginClass: LocationWebPlugin
        fileName: location_web.dart
