name: location_web
description: The web implementation of the location plugin.
version: 3.1.1
homepage: https://github.com/Lyokone/flutterlocation
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  js: ^0.6.3
  location_platform_interface:
    git:
      url: git@github.com:craggy2593/flutterlocation.git
      path: packages/location_platform_interface
      ref: develop
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: LocationWebPlugin
        fileName: location_web.dart
